# Generated by Django 4.2.5 on 2024-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_blog_author_alter_blog_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='authors',
        ),
    ]
